version: '3'

services:

  mongodb:
    image: mongo:4.2.8
    #image: mongo:4.0.8
    command: mongod --auth
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: mongodbpassword
      MONGO_INITDB_DATABASE: journey
    volumes: 
     - ./data:/data/db

  api:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    environment:
      HOST: 0.0.0.0  
      PORT: 5000
      MONGODB_DATABASE: journey
      MONGODB_USERNAME: mongodbuser
      MONGODB_PASSWORD: mongodbpassword
      MONGODB_HOSTNAME: mongodb
      API_URL: "http://localhost:5000"
    depends_on:
      - mongodb